"""Calculatuions model

Revision ID: 993f410aaef9
Revises: 3b401ac4f4e9
Create Date: 2024-11-04 12:03:59.600291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993f410aaef9'
down_revision = '3b401ac4f4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data_set',
    sa.Column('id_name', sa.Integer(), nullable=False),
    sa.Column('name_of_the_feature', sa.String(length=50), nullable=True),
    sa.Column('frequency_1', sa.String(length=10), nullable=True),
    sa.Column('frequency_2', sa.String(length=10), nullable=True),
    sa.Column('probability_1', sa.String(length=5), nullable=True),
    sa.Column('probability_2', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id_name')
    )
    with op.batch_alter_table('user_data_set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_data_set_name_of_the_feature'), ['name_of_the_feature'], unique=True)

    op.drop_table('UserDataSet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserDataSet',
    sa.Column('id_name', sa.INTEGER(), nullable=True),
    sa.Column('name_of_the_feature', sa.TEXT(), nullable=True),
    sa.Column('frequency_1', sa.NUMERIC(), nullable=True),
    sa.Column('frequency_2', sa.NUMERIC(), nullable=True),
    sa.Column('probability_1', sa.NUMERIC(), nullable=True),
    sa.Column('probability_2', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('name_of_the_feature')
    )
    with op.batch_alter_table('user_data_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_data_set_name_of_the_feature'))

    op.drop_table('user_data_set')
    # ### end Alembic commands ###
