"""Calculatuions model

Revision ID: cad35a7f5d7d
Revises: 57b460091618
Create Date: 2024-11-04 22:39:52.109434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad35a7f5d7d'
down_revision = '57b460091618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_the_feature', sa.String(length=50), nullable=True),
    sa.Column('frequency_1', sa.String(length=10), nullable=True),
    sa.Column('frequency_2', sa.String(length=10), nullable=True),
    sa.Column('probability_1', sa.String(length=5), nullable=True),
    sa.Column('probability_2', sa.String(length=5), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_data_set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_data_set_name_of_the_feature'), ['name_of_the_feature'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_data_set_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_data_set_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_data_set_name_of_the_feature'))

    op.drop_table('user_data_set')
    # ### end Alembic commands ###
